research_task:
  description: >
    Conduct a thorough research about {topic} for {company}, expert advice in {topic}Make sure you find any interesting and relevant information given the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic} for {company}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report. Make sure the report is detailed and contains any and all relevant information.
    Your report should:
      1. Begin with an executive summary
      2. Include all key information from the research
      3. Provide insightful analysis of trends and patterns
      4. Offer a market outlook for company, noting that this should not be used for trading decisions
      5. Be formatted in a professional, easy-to-read style with clear headings
  
  expected_output: >
    A polished, professional report on {company} that presents the research
    findings with added analysis and insights. The report should be well-structured
    with an executive summary, main sections, and conclusion.
    Formatted as markdown without '```'

  agent: reporting_analyst
  context:
    - research_task
  
  output_file: report.md
